# Generated by Django 4.2.4 on 2023-08-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostProdInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(verbose_name='season')),
                ('region', models.PositiveIntegerField(choices=[(1, 'Gulf'), (2, 'Maritimes'), (3, 'Quebec'), (4, 'Newfoundland')], verbose_name='region')),
                ('name', models.CharField(max_length=1000, verbose_name='post-production environment name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('port', models.PositiveIntegerField(verbose_name='proxy port')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'ordering': ['season', 'region', 'name'],
            },
        ),
    ]
